#!/bin/sh

# Check number of params
[ $# -ne 1 ] && [ $# -ne 2 ] && \
    echo "Usage: category <project.git> <category>" && exit 1

# Set the project name, adding .git if necessary
p=$(echo "$1" | sed 's/\.git$\|$/.git/i')

[ ! -d "$p" ] && echo "$p not found."

[ -n "$2" ] && echo "$2" > "$p/category" \
    || rm -f "$p/category"
